[build]
publish = "web/"
command = "npm run build"
functions = "netlify-functions"

[[redirects]]
from = "/letterboxd"
to = "/.netlify/functions/fetch-letterboxd"
status = 200

[[redirects]]
from = "/steam"
to = "/.netlify/functions/fetch-steam"
status = 200
